spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/regsitration
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    